[package]
name = "string-case"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "String case"
license = "MIT OR Apache-2.0"

[dependencies]
either = { version = "1", default-features = false }
